name: Python check

on:
  push:
  pull_request:

jobs:
  py-compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Compile main app
        run: python -m py_compile stereo_depth_camera_app.py
